(function(){try{
(function(){
  'use strict';
  const KEY='xy-home-v2:outfit-records-v1';
  const phone=document.querySelector('.phone'),grid=document.querySelector('#page-phone .app-grid');
  if(!phone||!grid)return;
  const app=document.createElement('div');app.className='app';app.dataset.app='outfit';app.dataset.deskWidget='app-outfit';app.setAttribute('role','button');app.tabIndex=0;app.setAttribute('aria-label','穿搭记录');
  app.innerHTML='<div class="app-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"><path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4c-1 3-7 3-8 0Z"/></svg></div><div class="app-name">穿搭记录</div>';grid.appendChild(app);
  const page=document.createElement('section');page.className='page full';page.id='page-outfit';page.hidden=true;
  page.innerHTML='<header class="oj-head"><button data-act="back" aria-label="返回首页">‹ 返回</button><h2>穿搭记录</h2><button data-act="add" aria-label="添加今日穿搭">＋</button></header><main class="oj-main"><div class="oj-top"><div><div class="oj-period"></div><div class="oj-small">每周穿搭手账</div></div><div class="oj-switch"><button data-act="week" aria-pressed="true">周视图</button><button data-act="month" aria-pressed="false">月视图</button></div></div><div class="oj-navigation"><button data-act="today">回到本周</button><div class="oj-arrows"><button data-act="prev" aria-label="上一周">‹</button><button data-act="next" aria-label="下一周">›</button></div></div><div class="oj-calendar"></div><div class="oj-footer"><span class="oj-count"></span><span>点日期查看或添加</span></div><section class="oj-editor" hidden><div class="oj-editor-title"><h3></h3><button data-act="close" aria-label="关闭编辑">×</button></div><label>日期<input class="oj-edit-date" type="date" required></label><div class="oj-editor-photo"></div><label>穿搭名称<input class="oj-name" maxlength="40" placeholder="例如：今天的学院风"></label><label>心情 / 备注<textarea class="oj-note" maxlength="500" placeholder="想记下的细节…"></textarea></label><label>添加或替换图片<input class="oj-file" type="file" accept="image/*"></label><div class="oj-actions"><button data-act="save" class="oj-save">保存记录</button><button data-act="remove-photo">移除图片</button><button data-act="delete" class="oj-delete">删除记录</button></div><div class="oj-status" role="status" aria-live="polite"></div></section></main>';
  phone.insertBefore(page,phone.querySelector('.tabbar'));
  const $=s=>page.querySelector(s);let records={},anchor=new Date(),view='week',selected='',draftImage='',busy=false,tabDisplay='',reminderHidden=true;
  const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const parse=s=>new Date(s+'T12:00:00');
  const valid=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(parse(s).getTime())&&key(parse(s))===s;
  const plus=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x;};
  const start=d=>plus(d,-((d.getDay()+6)%7));
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeImage=s=>typeof s==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(s)?s:'';
  const picture=r=>safeImage(r?.image)?`<img loading="lazy" src="${esc(r.image)}" alt="${esc(r.name||'穿搭照片')}">`:'<span>＋</span><span>添加照片</span>';
  async function load(){if(typeof window.idbGet!=='function')throw Error('存储尚未就绪，请稍后重试');let data=await window.idbGet(KEY);if(typeof data==='string')data=JSON.parse(data);records={};if(data?.version===1&&data.records&&typeof data.records==='object')for(const [d,r]of Object.entries(data.records)){if(valid(d)&&r&&typeof r==='object')records[d]={name:String(r.name||''),note:String(r.note||''),image:safeImage(r.image),updatedAt:r.updatedAt};}}
  async function persist(next){const value=JSON.stringify({version:1,records:next});const ok=await window.idbSet(KEY,value);if(ok!==true)throw Error('保存未确认，请不要关闭页面，稍后重试');records=next;}
  function status(t){$('.oj-status').textContent=t;}
  function render(){const first=view==='week'?start(anchor):new Date(anchor.getFullYear(),anchor.getMonth(),1,12);$('.oj-period').textContent=view==='week'?`${first.getMonth()+1}月${first.getDate()}日 — ${plus(first,6).getMonth()+1}月${plus(first,6).getDate()}日`:`${anchor.getFullYear()}年 ${anchor.getMonth()+1}月`;page.querySelector('[data-act=week]').setAttribute('aria-pressed',String(view==='week'));page.querySelector('[data-act=month]').setAttribute('aria-pressed',String(view==='month'));page.querySelector('[data-act=today]').textContent=view==='week'?'回到本周':'回到本月';page.querySelector('[data-act=prev]').setAttribute('aria-label',view==='week'?'上一周':'上个月');page.querySelector('[data-act=next]').setAttribute('aria-label',view==='week'?'下一周':'下个月');let html='',count=0;
    if(view==='week'){html='<div class="oj-grid">';for(let i=0;i<7;i++){const d=plus(first,i),k=key(d),r=records[k];if(r)count++;html+=`<button class="oj-day ${k===key(new Date())?'today':''}" data-date="${k}" aria-label="${k} ${esc(r?.name||'添加穿搭')}"><div class="oj-date"><span>${['周一','周二','周三','周四','周五','周六','周日'][i]}</span><span>${d.getMonth()+1}/${d.getDate()}</span></div><div class="oj-photo">${picture(r)}</div><div class="oj-look-note">${esc(r?.name||'还没记录')}</div></button>`;}html+='<div class="oj-summary"><strong>这一周</strong><span>一张照片，<br>一种心情。</span></div></div>';}
    else{html='<div class="oj-month">'+['一','二','三','四','五','六','日'].map(d=>`<div class="oj-weekday">${d}</div>`).join('');for(let i=0;i<(first.getDay()+6)%7;i++)html+='<div></div>';const days=new Date(anchor.getFullYear(),anchor.getMonth()+1,0).getDate();for(let n=1;n<=days;n++){const k=key(new Date(anchor.getFullYear(),anchor.getMonth(),n,12)),r=records[k];if(r)count++;html+=`<button class="oj-month-day ${k===key(new Date())?'today':''}" data-date="${k}" aria-label="${k} ${esc(r?.name||'添加穿搭')}">${n}${safeImage(r?.image)?`<img loading="lazy" src="${esc(r.image)}" alt="${esc(r.name||'穿搭照片')}">`:r?'<span class="oj-dot"></span>':''}</button>`;}html+='</div>';}
    $('.oj-calendar').innerHTML=html;$('.oj-count').textContent=`${view==='week'?'本周':'本月'}已记录 ${count} 天`;
  }
  function edit(d){if(busy)return;selected=d;const r=records[d];draftImage=safeImage(r?.image);$('.oj-editor').hidden=false;$('.oj-editor h3').textContent='记录这一天';$('.oj-edit-date').value=d;$('.oj-name').value=r?.name||'';$('.oj-note').value=r?.note||'';$('.oj-file').value='';$('.oj-editor-photo').innerHTML='<div class="oj-photo">'+picture({image:draftImage,name:r?.name})+'</div>';status('图片保存在本机；请定期导出完整备份。');$('.oj-editor').scrollIntoView({block:'nearest',behavior:'smooth'});}
  async function imageData(file){if(file.size>25*1024*1024)throw Error('图片超过 25MB，请选择较小图片');if(!file.type.startsWith('image/'))throw Error('请选择图片');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const ratio=Math.min(1,1400/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(image.naturalHeight*ratio));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.85);}finally{URL.revokeObjectURL(url);}}
  async function open(){try{if(!window.__mochiDataReady)await new Promise((resolve,reject)=>{const done=()=>{clearTimeout(timer);document.removeEventListener('mochi-restore-done',done);resolve();};const timer=setTimeout(()=>{document.removeEventListener('mochi-restore-done',done);reject(Error('正在恢复数据，请稍后再打开穿搭记录'));},8000);document.addEventListener('mochi-restore-done',done);});await load();document.querySelectorAll('.phone > .page').forEach(p=>p.hidden=true);page.hidden=false;const reminder=document.getElementById('backup-remind-bar');if(reminder){reminderHidden=reminder.hidden;reminder.hidden=true;}const tab=phone.querySelector('.tabbar');if(tab){tabDisplay=tab.style.display;tab.style.display='none';}anchor=new Date();render();}catch(e){alert(e.message);}}
  function back(){if(busy)return;page.hidden=true;document.getElementById('page-phone').hidden=false;const tab=phone.querySelector('.tabbar');if(tab)tab.style.display=tabDisplay;const reminder=document.getElementById('backup-remind-bar');if(reminder)reminder.hidden=reminderHidden;$('.oj-editor').hidden=true;}
  app.addEventListener('click',e=>{e.stopPropagation();open();});app.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});
  $('.oj-file').addEventListener('change',async()=>{const f=$('.oj-file').files[0];if(!f||busy)return;busy=true;status('正在处理图片…');try{draftImage=await imageData(f);$('.oj-editor-photo').innerHTML='<div class="oj-photo">'+picture({image:draftImage})+'</div>';status('图片已就绪，点击保存记录。');}catch(e){status(e.message);}finally{busy=false;}});
  page.addEventListener('click',async e=>{const day=e.target.closest('[data-date]');if(day){edit(day.dataset.date);return;}const action=e.target.closest('[data-act]')?.dataset.act;if(!action||busy)return;
    if(action==='back'){back();return;}if(action==='add'){edit(key(new Date()));return;}if(action==='close'){$('.oj-editor').hidden=true;return;}if(action==='remove-photo'){draftImage='';$('.oj-editor-photo').innerHTML='<div class="oj-photo">'+picture(null)+'</div>';status('点击保存记录后移除图片。');return;}
    if(action==='week'||action==='month'){view=action;render();return;}if(action==='today'){anchor=new Date();render();return;}if(action==='prev'||action==='next'){const n=action==='prev'?-1:1;anchor=view==='week'?plus(anchor,n*7):new Date(anchor.getFullYear(),anchor.getMonth()+n,1,12);render();return;}
    if(action==='save'||action==='delete'){const d=$('.oj-edit-date').value;if(!valid(d)){status('请选择有效日期');return;}if(action==='delete'&&!confirm('删除 '+selected+' 的穿搭记录？'))return;if(action==='save'&&d!==selected&&records[d]&&!confirm('该日期已有记录，要替换吗？'))return;busy=true;status('正在保存…');try{const next={...records};if(action==='delete')delete next[selected];else{delete next[selected];next[d]={name:$('.oj-name').value.trim()||'今日穿搭',note:$('.oj-note').value.trim(),image:draftImage,updatedAt:Date.now()};}await persist(next);anchor=parse(d);render();status(action==='delete'?'记录已删除':'已保存到本机');}catch(e){status(e.message);}finally{busy=false;}}
  });
  document.addEventListener('mochi-restore-done',()=>{if(!page.hidden)load().then(render).catch(e=>status(e.message));});
})();
window.__mochiLoaded.push("outfit-journal.js");
}catch(e){console.error("outfit-journal.js",e);window.__jsErrors.push("outfit-journal.js: "+String(e));window.__mochiErrLoaded.push("outfit-journal.js");}})();